filepath: /home/baymin/tflearn/examples/images/
#python文件路径和模型的路径
pythonpath: /home/baymin/tflearn/examples/images/vgg_network_recognize.py
istest: 0

server:
  port: 8082

spring:
  http:
    multipart:
      enabled: true
      max-file-s ize: 30MB
      max-request-size: 30MB