kuayu-origin: "*"
kuayu-methods: POST,GET,PATCH,OPTIONS,HEAD,DELETE
kuayu-max-age: 3600
kuayu-headers: reffers, Authorization, Origin, X-Requested-With, Content-Type, Accept
#PCB
pcbpath: /home/baymin/pcb_img/
pcbTestingUrl: http://192.168.31.182
pcbResultUrl: http://localhost
pcbRestartShellPath: /home/baymin/tt.sh
#pcbOutNetAIImageBaseUrl: http://aitest.qtingvision.com:888/aiimg/ #外网访问图片的基本路径
#pcbOutNetExportBaseUrl: http://aitest.qtingvision.com:888/excel/ #外网访问图片的基本路径
pcbOutNetAIImageBaseUrl: http://101.64.34.145:888/aiimg/ #外网访问图片的基本路径
pcbOutNetExportBaseUrl: http://101.64.34.145:888/excel/ #外网访问图片的基本路径

pcbServiceStart: /opt/ai/start-by-port.sh #中间端口号可以替换成真实的端口号
pcbServiceStop: /opt/ai/stop-by-port.sh #空格加端口号
pcbServiceSearch: /opt/ai/search-by-port.sh #空格加端口号

excelPath: /opt/lampp/htdocs/excel/
#PCB

#Shangfei
ShangfeiTestingUrl: http://192.168.31.182:8192
#Shangfei



filepath: /home/baymin/



baidu-app-id: 11504520
baidu-api-key: pHn96o7ZZ7wzLauHLQU0Xeam
baidu-secret-key: TfdM82oDfb46Ku5cj1t85TtOuzGWjCO3


face-api-key: TWUdTxmes7PPUzkv7tDJuHqPrrOrhA5q
face-api-secret: jprPaWyPZqXJdjFAEgXacdJ5iypSCPHa


#车牌参数
platepath: /home/baymin/upload_plate/
plateurl: http://localhost:8071
#车牌参数

#python文件路径和模型的路径
pythonpath: /home/baymin/tflearn/examples/images/vgg_network_recognize.py
#文本框识别的
shpath: /home/icubic/xie/detectron/test2.sh

istest: 0
isbaidu: 0

# mysql
spring:
  # 环境 dev|test|pro
  profiles:
    active: vip
  http:
    multipart:
      enabled: true
      max-file-s ize: 30MB
      max-request-size: 30MB