kuayu-origin: "*"
kuayu-methods: POST,GET,PATCH,OPTIONS,HEAD,DELETE
kuayu-max-age: 3600
kuayu-headers: reffers, Authorization, Origin, X-Requested-With, Content-Type, Accept
#PCB
pcbpath: /home/baymin/pcb_img/
pcbTestingUrl: http://192.168.31.182
pcbResultUrl: http://localhost
pcbRestartShellPath: /home/baymin/tt.sh
#PCB




filepath: /home/baymin/



baidu-app-id: 11504520
baidu-api-key: pHn96o7ZZ7wzLauHLQU0Xeam
baidu-secret-key: TfdM82oDfb46Ku5cj1t85TtOuzGWjCO3


face-api-key: TWUdTxmes7PPUzkv7tDJuHqPrrOrhA5q
face-api-secret: jprPaWyPZqXJdjFAEgXacdJ5iypSCPHa


#车牌参数
platepath: /home/baymin/upload_plate/
plateurl: http://localhost:8071
#车牌参数

#python文件路径和模型的路径
pythonpath: /home/baymin/tflearn/examples/images/vgg_network_recognize.py
#文本框识别的
shpath: /home/icubic/xie/detectron/test2.sh

istest: 0
isbaidu: 0

# mysql
spring:
  # 环境 dev|test|pro
  profiles:
    active: vip
  http:
    multipart:
      enabled: true
      max-file-s ize: 30MB
      max-request-size: 30MB